spring:
  datasource:
    driverClassName: org.h2.Driver
    password:
    url: jdbc:h2:tcp://localhost/~/test;MODE=Mysql;
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true